### ISSUE TITLE
TypeError when canceling save-dialog

### ISSUE THREAD

**Issue by chincherpa** [Burakcoli/Abstract-Art-Generator#3]
https://github.com/Burakcoli/Abstract-Art-Generator/blob/139096e57f659a2aca7eaff1ae465a9e226d4f70/art_generator.py#L1281

just adding?:

if path:
  ...

**Comment by Burakcoli** [comment]
Yes, it's done now.

**Comment by chincherpa** [comment]
Sorry!
didn't check the closed issues, obviously...

great program ;)
